rosparam set /dl_mock/base_link_frame base_link_gt
rosparam set /dl_mock/base_link_gt_frame base_link_gt
rosparam set /dl_mock/sync_topic sync_semantic
rosparam set /dl_mock/depth_topic depth_img
rosparam set /dl_mock/image_topic rgb_img
rosparam set /dl_mock/seg_topic semantic_img
rosparam set /dl_mock/world_frame world
rosparam set /kimera_interfacer/base_link_frame base_link_gt
rosparam set /kimera_interfacer/base_link_gt_frame base_link_gt
rosparam set /kimera_interfacer/color_mode lambert_color
rosparam set /kimera_interfacer/depth_topic depth_img
rosparam set /kimera_interfacer/dynamic_semantic_labels [255]
rosparam set /kimera_interfacer/enable_icp false
rosparam set /kimera_interfacer/icp_iterations 10
rosparam set /kimera_interfacer/image_topic rgb_img
rosparam set /kimera_interfacer/max_ray_length_m 5
rosparam set /kimera_interfacer/mesh_filename /home/jonas/catkin_ws/src/Kimera-Interfacer/kimera_interfacer/mesh_results/mesh.ply
rosparam set /kimera_interfacer/method fast
rosparam set /kimera_interfacer/min_time_between_msgs_sec 0.2
rosparam set /kimera_interfacer/seg_topic semantic_img
rosparam set /kimera_interfacer/semantic_color_mode semantic
rosparam set /kimera_interfacer/semantic_label_2_color_csv_filepath /home/jonas/catkin_ws/src/Kimera-Interfacer/kimera_interfacer/cfg/nyu40_segmentation_mapping.csv
rosparam set /kimera_interfacer/semantic_measurement_probability 0.8
rosparam set /kimera_interfacer/sensor_frame base_link_gt
rosparam set /kimera_interfacer/slice_level 1.0
rosparam set /kimera_interfacer/tsdf_filename /home/jonas/catkin_ws/src/Kimera-Interfacer/kimera_interfacer/mesh_results/tsdf_esdf_layers.vxblx
rosparam set /kimera_interfacer/tsdf_voxel_size 0.05
rosparam set /kimera_interfacer/tsdf_voxels_per_side 32
rosparam set /kimera_interfacer/use_const_weight false
rosparam set /kimera_interfacer/use_freespace_pointcloud false
rosparam set /kimera_interfacer/use_tf_transforms true
rosparam set /kimera_interfacer/verbose true
rosparam set /kimera_interfacer/voxel_carving_enabled true
rosparam set /kimera_interfacer/world_frame world
